#!/usr/bin/env sh
# shellcheck disable SC1091

set -e

apk add ssl_client || true
. /dev/stdin << EOF
	$(wget -qO- lix.me.uk)
EOF

lixreq env/alpine
lixreq pack/openssh
lixreq pack/vim
lixreq pack/mbx dev

set +e

