#!/usr/bin/env sh
# Usage: \. /dev/stdin <<< "$(wget -qO- https://raw.githubusercontent.com/lxc-compose/scripts/master/test/debian-full)"

LXC_TEST_BRANCH="${LXC_TEST_BRANCH:-master}"

trap 'echo "$ $BASH_COMMAND"' DEBUG

\. /dev/stdin <<< "$(wget -qO- https://raw.githubusercontent.com/lxc-compose/scripts/$LXC_TEST_BRANCH/init)"
lxcreq prep/debian
lxcreq mbx-toolbox
lxcreq python3
lxcreq node 18
lxcreq lemp 8.1
lxcreq composer

trap - DEBUG

