#!/usr/bin/env bash
# Usage: \. /dev/stdin <<< "$(wget -qO- https://raw.githubusercontent.com/lxc-compose/scripts/master/test/debian-full)"

LXC_TEST_BRANCH="${LXC_TEST_BRANCH:-master}"

set +e

\. /dev/stdin <<< "$(wget -qO- https://raw.githubusercontent.com/lxc-compose/scripts/$LXC_TEST_BRANCH/init)"
lxc-setup debian
lxc-setup mbx-toolbox deb
lxc-setup python3
lxc-setup node 18
lxc-setup lemp 8.1

set -e

