#!/usr/bin/env bash
# Usage: lxc-setup debian

set +e

me=$(basename "${BASH_SOURCE[0]}")

# lxc-setup lib/common

dpkg-reconfigure locales
apt-get update && apt-get full-upgrade -y
apt-get autoremove -y

$DCODE="deb"

set -e

