#!/usr/bin/env sh
# Usage: lixreq autopatch <crontime: "5 4 * * *">

set +e

me="autopatch"
echo ''
echo === Setup $me ===

if [ "$ENV_DIST_NAME" == "alpine" ]; then
	# pkgreq apk-autoupdate # not stable yet
	sed -i '/#LIXPOSE:autopatch/d' /etc/crontabs/$USER
	echo "$1 apk update > \$HOME/autopatch.log 2>&1 && apk upgrade >> \$HOME/autopatch.log 2>&1 && reboot #LIXPOSE:autopatch" >> /etc/crontabs/$USER
elif [ "$ENV_DIST_NAME" == "debian" ]; then
	# TODO: Unattended-Upgrades for Debian systems
elif [ "$ENV_DIST_NAME" == "redhat" ]; then
	# TODO: Auto security patches for RedHat systems
fi

set -e

