#!/usr/bin/env sh
# Usage: \. /dev/stdin << EOF
# $(wget -qO- lix.me.uk)
# EOF

set +e

test -n "$LIX_SETUP_BASE_URL" || LIX_SETUP_BASE_URL="https://raw.githubusercontent.com/lixpose/scripts/master"

wexec() {
	url="$1"
	shift
	if command -v "curl" > /dev/null 2>&1; then
		\. /dev/stdin << EOF 
			$(curl -s "$url")
EOF
	elif command -v "wget" > /dev/null 2>&1; then
		\. /dev/stdin << EOF 
			$(wget -qO- "$url")
EOF
	else
		echo "No curl or wget found." >&2
		return 1
	fi
}

lixreq() {
	path="$1"
	shift
	if [ -z "$LIX_SETUP_LOCAL_PATH" ]; then
		wexec "$LIX_SETUP_BASE_URL/$path" "$@"
	else
		"$LIX_SETUP_LOCAL_PATH/$path" "$@"
	fi
}

lixreq lib/common

set -e

