#!/usr/bin/env bash
# Usage: \. /dev/stdin <<< "$(wget -qO- https://raw.githubusercontent.com/lxc-compose/scripts/master/init)"

set +e

LXC_SETUP_BASE_URL="${LXC_SETUP_BASE_URL:-https://raw.githubusercontent.com/lxc-compose/scripts/master}"

wexec() {
	url="$1"
	shift
	if command -v "curl" &>/dev/null; then
		\. /dev/stdin <<< "$(curl --proto '=https' --tlsv1.2 -s "$url")"
	elif command -v "wget" &>/dev/null; then
		\. /dev/stdin <<< "$(wget --secure-protocol=TLSv1_2 -qO- "$url")"
	else
		echo "No curl or wget found." >&2
		return 1
	fi
}

lxcreq() {
	wexec "$LXC_SETUP_BASE_URL/$1"
}

lxcreq lib/common

set -e

