#!/usr/bin/env bash
# Usage: lxc-setup lemp <phpversion: {N.N}>

set +e

me=$(basename "${BASH_SOURCE[0]}")
echo ''
echo === Setup $me ===
phpversion=$1

[ -n "$phpversion" ] || { >&2 echo "$me: Parameter 1 is missing: phpversion"; exit 1; } 

lxc-setup lib/common

if ! test-command nginx; then
	ensure-installed nginx
	rm /etc/nginx/sites-enabled/default
	rm -r /var/www/html
	systemctl start nginx
fi

if ! test-command php; then
	ensure-installed wget
	ensure-installed zip
	ensure-installed unzip
	if [ "$DCODE" = "deb" ]; then
		ensure-installed lsb-release
		wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
		echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/php$phpversion.list
		apt-get update
	fi
	ensure-installed \
		php$phpversion \
		php$phpversion-common \
		php$phpversion-cli \
		php$phpversion-curl \
		php$phpversion-gd \
		php$phpversion-gmp \
		php$phpversion-imap \
		php$phpversion-intl \
		php$phpversion-mbstring \
		php$phpversion-mysql \
		php$phpversion-soap \
		php$phpversion-sqlite3 \
		php$phpversion-xml \
		php$phpversion-xmlrpc \
		php$phpversion-zip \
		php$phpversion-fpm
			systemctl start php$phpversion-fpm
			systemctl restart nginx
fi

if ! test-command mysql; then
	ensure-installed mariadb-server
fi

set -e

