#!/usr/bin/env sh
# Usage: lixreq lemp <phpversion: {N.N}>

set +e

me="lemp"
echo ''
echo === Setup $me ===
phpversion="$1"

test -n "$phpversion" || { echo "$me: Parameter 1 is missing: phpversion" >&2; exit 1; } 

lixreq nginx
lixreq mariadb
lixreq php $phpversion
pkgreq php$phpversion-fpm
svcrunany php$phpversion-fpm php-fpm$phpversion
svcrun nginx

set -e

