#!/usr/bin/env sh
# Usage: lixreq mbx <branch: [ master | dev ]?>

set +e

me="mbx"
echo ''
echo === Setup $me ===
branch=${1-master}

if [ -z "$MBX_VERSION" ]; then
	mbxpath=/usr/local/mbx
	mkdir -p $mbxpath
	pkgreq git
	git clone --depth 1 https://github.com/martin-braun/mbx-toolbox.git $mbxpath
	echo '' >> $HOME/.bashrc
	echo '# mbx' >> $ENV_SHELL_RC
	echo 'export MBX_PATH="'"$mbxpath"'"' >> $ENV_SHELL_RC
	echo 'export PATH=$PATH:/$MBX_PATH/bin/'"$ENV_DIST_CODE"':$MBX_PATH/bin' >> $ENV_SHELL_RC
	echo 'test -e "$MBX_PATH/lib/init.sh" && \. "$MBX_PATH/lib/init.sh"' >> $ENV_SHELL_RC
	sourcerc
	if [ "$branch" = "dev" ]; then
		git -C "$mbxpath" config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
		git -C "$mbxpath" fetch --all
		git -C "$mbxpath" checkout dev
		mbx-upgrade
	fi
fi

set -e

