#!/usr/bin/env bash
# Usage: lxcreq mbx-toolbox <branch: [ master | dev ]?>

set +e

me="mbx-toolbox"
echo ''
echo === Setup $me ===
branch=${1=-master}

lxcreq lib/common

if ! testc mbx-version; then
	mbxpath=/usr/local/mbx
	mkdir -p $mbxpath
	req git
	git clone --depth 1 https://github.com/martin-braun/mbx-toolbox.git /usr/local/mbx
	echo '' >> $HOME/.bashrc
	echo "export PATH=\$PATH:$mbxpath/bin/$DCODE:$mbxpath/bin" >> $HOME/.bashrc
	echo "test -e $mbxpath/lib/init.bash && . $mbxpath/lib/init.bash" >> $HOME/.bashrc
	\. "$HOME/.bashrc"
	if [ "$branch" = "dev" ]; then
		git -C "$mbxpath" config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
		git -C "$mbxpath" fetch --all
		git -C "$mbxpath" checkout dev
		mbx-upgrade
	fi
fi

set -e

