#!/usr/bin/env sh
# Usage: lixreq node <majorversion: {N}>

set +e

me="node"
echo ''
echo === Setup $me ===
majorversion=${1=-lts}

test -n "$majorversion" || { >&2 echo "$me: Parameter 1 is missing: majorversion"; exit 1; } 

if ! testc nvm; then
	pkgreq curl
	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
	source $HOME/.bashrc
fi

if [ "$majorversion" = "lts" ]; then
	nvm install --lts
	nvm alias default 'lts/*'
else
	nvm install $majorversion
	nvm alias default $majorversion
fi

if ! testc pm2; then
	npm i pm2 -g
fi

set -e

