#!/usr/bin/env bash
# Usage: lxcreq node <majorversion: {N}>

set +e

me="node"
echo ''
echo === Setup $me ===
majorversion=$1

[ -n "$majorversion" ] || { >&2 echo "$me: Parameter 1 is missing: majorversion"; exit 1; } 

lxcreq lib/common

if ! testc nvm; then
	pkgreq curl
	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
	source $HOME/.bashrc
	nvm install $majorversion
	nvm alias default $majorversion
elif [ $(node -v | tr "." "\n" | head -1 2>&1) != "v$majorversion" ]; then
	nvm install $majorversion
	nvm alias default $majorversion
fi

if ! testc pm2; then
	npm i pm2 -g
fi

set -e

