#!/usr/bin/env sh
# Usage: lixreq python3

set +e

me="python3"
echo ''
echo === Setup $me ===

pkgreq python3
pkgreq python3-pip 2> /dev/null || pkgreq py3-pip 2> /dev/null \
	|| { echo "Neither python3-pip nor py3-pip could be installed" >&2 && return 1; }

set -e

