#!/usr/bin/env bash
# Usage: lxcreq debian

set +e

me="prep/debian"
echo ''
echo === Setup $me ===

# lxcreq lib/common

dpkg-reconfigure locales
apt-get update && apt-get full-upgrade -y
apt-get autoremove -y

export DCODE="deb"

set -e

