#!/usr/bin/env bash
# Usage: lxc-setup redhat

set +e

me=$(basename "${BASH_SOURCE[0]}")

lxc-setup lib/common

if test-command dnf; then
	dnf up --refresh -y
	dnf autoremove -y
elif test-command yum; then
	yum check-update
	yum upgrade -y
else
	echo No package manager found.
	return 1
fi

export DCODE="rh"

set -e

