#!/usr/bin/env sh
# Usage: lixreq pack/deno
# shellcheck disable SC2016

set -e

me="pack/deno"
echo ''
echo "=== Setup $me ==="

if ! testcmd deno; then
	pkgreq curl unzip
	curl -fsSL https://deno.land/x/install/install.sh | sh
	{
		echo ''
		echo '# deno';
		echo 'export PATH=$PATH:/$HOME/.deno/bin'
	} >> "$ENV_SHELL_RC"
	sourcerc
fi

set +e
