#!/usr/bin/env sh
# Usage: lixreq pack/mariadb

set -e

me="pack/mariadb"
echo ''
echo "=== Setup $me ==="

if ! testcmd mysql; then
	pkgreqany mariadb mariadb-server
	pkgreq mariadb-client || true
	/etc/init.d/mariadb setup || true
	svcrun mariadb || true
fi

set +e
