#!/usr/bin/env sh
# Usage: lixreq pack/vim

set -e

me="pack/vim"
echo ''
echo "=== Setup $me ==="

if ! testcmd vim; then
	pkgreq vim
fi

if [ ! -f "$USER_HOME/.vimrc" ]; then
	{
		echo set clipboard^=unnamed,unnamedplus
		echo set number
		echo set relativenumber
	} > "$USER_HOME/.vimrc"
fi

set +e

