#!/usr/bin/env sh
# Usage: lixreq pack/vim

set -e

me="pack/vim"
echo ''
echo === Setup $me ===

if ! testcmd vim; then
	pkgreq vim
fi

if [ ! -f "$HOME/.vimrc" ]; then
	echo set clipboard^=unnamed,unnamedplus > $HOME/.vimrc
	echo set number >> $HOME/.vimrc
	echo set relativenumber >> $HOME/.vimrc
fi

set +e

