#!/usr/bin/env sh
# Usage: lixreq alpine <libc: [ 'musl' | 'g' ]?> <utils: [ 'bb' | 'gnu' ]?> <branch: v{N.NN}?
# g = gcompat, bb = busybox

set +e

export ENV_DIST_NAME="alpine"
export ENV_DIST_CODE="alp"
test -n "$ENV_SHELL_RC" || export ENV_SHELL_RC="$HOME/.profile"

me="env/$ENV_DIST_NAME"
echo ''
echo === Setup $me ===
branch="$1"

if [ -n "$branch" ]; then
	sed -i "s#alpinelinux\\.org/alpine/.\*/#alpinelinux.org/alpine/$branch/#g" /etc/apk/repositories
fi

echo '' > /etc/motd
apk update
apk upgrade

if [ "$1" = "g" ]; then
	pkgreq gcompat
fi

if [ "$2" = "gnu" ]; then
	pkgreq util-linux pciutils usbutils coreutils binutils findutils grep iproute2
fi

sourcerc # sourcing right after env setup will prevent unintended re-installs

set -e

