#!/usr/bin/env sh
# Usage: lxcreq alpine <libc: [ 'musl' | 'g' ]?> <utils: [ 'busybox' | 'gnu' ]?>

set +e

export ENV_DIST_NAME="alpine"
export ENV_DIST_CODE="alp"
test -n "$ENV_SHELL_RC" || export ENV_SHELL_RC="$HOME/.profile"

me="env/$ENV_DIST_NAME"
echo ''
echo === Setup $me ===

apk update
apk upgrade

if [ "$1" = "g" ]; then
	apk add gcompat
fi

if [ "$2" = "gnu" ]; then
	apk add util-linux pciutils usbutils coreutils binutils findutils grep iproute2
fi

set -e

