#!/usr/bin/env sh
# Usage: lixreq env/debian

set +e

export ENV_DIST_NAME="debian"
export ENV_DIST_CODE="deb"
test -n "$ENV_SHELL_RC" || export ENV_SHELL_RC="$USER_HOME/.bashrc"

me="env/$ENV_DIST_NAME"
echo ''
echo === Setup $me ===

dpkg-reconfigure locales
apt-get update && apt-get full-upgrade -y
apt-get autoremove -y

sourcerc # sourcing right after env setup will prevent unintended re-installs

set -e

