#!/usr/bin/env sh
# Usage: lixreq redhat

set +e

export ENV_DIST_NAME="redhat"
export ENV_DIST_CODE="rh"
test -n "$ENV_SHELL_RC" || export ENV_SHELL_RC="$HOME/.bashrc"

me="env/$ENV_DIST_NAME"
echo ''
echo === Setup $me ===

if testcmd dnf; then
	dnf up --refresh -y
	dnf autoremove -y
elif testcmd yum; then
	yum check-update
	yum upgrade -y
else
	echo No package manager found. >&2
	return 1001
fi

sourcerc # sourcing right after env setup will prevent unintended re-installs

set -e

