#!/usr/bin/env bash
# Usage: lxcreq redhat

set +e

me="env/redhat"
echo ''
echo === Setup $me ===

lxcreq lib/common

if testc dnf; then
	dnf up --refresh -y
	dnf autoremove -y
elif testc yum; then
	yum check-update
	yum upgrade -y
else
	echo No package manager found.
	return 1
fi

export DCODE="rh"

set -e

